version: '2'
services:
  redis-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
    build:
      context: .
      args:
        redis_version: '3.2.11'
    hostname: server
    ports:
      - '17000-17007:17000-17007'
